#!/bin/bash
set -e

case "$1" in
    remove|upgrade|deconfigure)
        xdg-desktop-menu uninstall /usr/share/applications/zotero.desktop
        xdg-mime uninstall /usr/share/mime/packages/zotero.xml
    ;;

    failed-upgrade)
    ;;

    *)
        echo "prerm called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

exit 0
